version: 0.2
phases:
  install:
    commands:
      - npm install
  pre_build:
   commands:
     - echo "pre_build step"
 build:
   commands:
     - - aws s3 sync . s3://edocument1 
  post_build:
    commands:
       - aws cloudfront create-invalidation --distribution-id E21YSL85YK05FF --paths '/*'