export const GET_DOCUMENTS_RESPONSE = 'GET_DOCUMENTS_RESPONSE';
export const GET_DOCUMENT_RESPONSE = 'GET_DOCUMENT_RESPONSE';
export const ADD_NEW_DOCUMENT_RESPONSE = 'ADD_NEW_DOCUMENT_RESPONSE';
export const UPDATE_EXISTING_DOCUMENT_RESPONSE = 'UPDATE_EXISTING_DOCUMENT_RESPONSE';
export const DELETE_DOCUMENT_RESPONSE = 'DELETE_DOCUMENT_RESPONSE';

export const GET_DOCTORS_RESPONSE = 'GET_DOCTORS_RESPONSE';
export const GET_PATIENTS_RESPONSE = 'GET_PATIENTS_RESPONSE';

export const API_CALL_BEGIN = 'API_CALL_BEGIN';
export const API_CALL_ERROR = 'API_CALL_ERROR';
